#!/bin/sh
set -eu

mkdir -p Adafruit_NeoPixel

ARDUINO_ROOT=/home/dek/arduino-1.6.3
ARDUINO_TOOLS=$ARDUINO_ROOT/hardware/tools/avr/bin

TMPDIR=/tmp/build4375631641947471586.tmp
rm -rf ${TMPDIR}
mkdir -p ${TMPDIR} ${TMPDIR}/Esplora

${ARDUINO_TOOLS}/avr-g++ -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=10603 -DARDUINO_AVR_ESPLORA -DARDUINO_ARCH_AVR -DUSB_VID=0x2341 -DUSB_PID=0x803c -DUSB_MANUFACTURER="Unknown" '-DUSB_PRODUCT="Arduino Esplora"' -I${ARDUINO_ROOT}/hardware/arduino/avr/cores/arduino -I${ARDUINO_ROOT}/hardware/arduino/avr/variants/leonardo -I${ARDUINO_ROOT}/libraries/Esplora/src joystick.cpp -o ${TMPDIR}/joystick.cpp.o 
${ARDUINO_TOOLS}/avr-g++ -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=10603 -DARDUINO_AVR_ESPLORA -DARDUINO_ARCH_AVR -DUSB_VID=0x2341 -DUSB_PID=0x803c -DUSB_MANUFACTURER="Unknown" '-DUSB_PRODUCT="Arduino Esplora"' -I${ARDUINO_ROOT}/hardware/arduino/avr/cores/arduino -I${ARDUINO_ROOT}/hardware/arduino/avr/variants/leonardo -I${ARDUINO_ROOT}/libraries/Esplora/src ${ARDUINO_ROOT}/libraries/Esplora/src/Esplora.cpp -o ${TMPDIR}/Esplora/Esplora.cpp.o 
${ARDUINO_TOOLS}/avr-gcc -c -g -Os -w -ffunction-sections -fdata-sections  -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=10603 -DARDUINO_AVR_ESPLORA -DARDUINO_ARCH_AVR -DUSB_VID=0x2341 -DUSB_PID=0x803c -DUSB_MANUFACTURER="Unknown" '-DUSB_PRODUCT="Arduino Esplora"' -I${ARDUINO_ROOT}/hardware/arduino/avr/cores/arduino -I${ARDUINO_ROOT}/hardware/arduino/avr/variants/leonardo ${ARDUINO_ROOT}/hardware/arduino/avr/cores/arduino/wiring_shift.c -o ${TMPDIR}/wiring_shift.c.o 
${ARDUINO_TOOLS}/avr-gcc -c -g -Os -w -ffunction-sections -fdata-sections  -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=10603 -DARDUINO_AVR_ESPLORA -DARDUINO_ARCH_AVR -DUSB_VID=0x2341 -DUSB_PID=0x803c -DUSB_MANUFACTURER="Unknown" '-DUSB_PRODUCT="Arduino Esplora"' -I${ARDUINO_ROOT}/hardware/arduino/avr/cores/arduino -I${ARDUINO_ROOT}/hardware/arduino/avr/variants/leonardo ${ARDUINO_ROOT}/hardware/arduino/avr/cores/arduino/WInterrupts.c -o ${TMPDIR}/WInterrupts.c.o 
${ARDUINO_TOOLS}/avr-gcc -c -g -Os -w -ffunction-sections -fdata-sections  -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=10603 -DARDUINO_AVR_ESPLORA -DARDUINO_ARCH_AVR -DUSB_VID=0x2341 -DUSB_PID=0x803c -DUSB_MANUFACTURER="Unknown" '-DUSB_PRODUCT="Arduino Esplora"' -I${ARDUINO_ROOT}/hardware/arduino/avr/cores/arduino -I${ARDUINO_ROOT}/hardware/arduino/avr/variants/leonardo ${ARDUINO_ROOT}/hardware/arduino/avr/cores/arduino/hooks.c -o ${TMPDIR}/hooks.c.o 
${ARDUINO_TOOLS}/avr-gcc -c -g -Os -w -ffunction-sections -fdata-sections  -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=10603 -DARDUINO_AVR_ESPLORA -DARDUINO_ARCH_AVR -DUSB_VID=0x2341 -DUSB_PID=0x803c -DUSB_MANUFACTURER="Unknown" '-DUSB_PRODUCT="Arduino Esplora"' -I${ARDUINO_ROOT}/hardware/arduino/avr/cores/arduino -I${ARDUINO_ROOT}/hardware/arduino/avr/variants/leonardo ${ARDUINO_ROOT}/hardware/arduino/avr/cores/arduino/wiring_analog.c -o ${TMPDIR}/wiring_analog.c.o 
${ARDUINO_TOOLS}/avr-gcc -c -g -Os -w -ffunction-sections -fdata-sections  -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=10603 -DARDUINO_AVR_ESPLORA -DARDUINO_ARCH_AVR -DUSB_VID=0x2341 -DUSB_PID=0x803c -DUSB_MANUFACTURER="Unknown" '-DUSB_PRODUCT="Arduino Esplora"' -I${ARDUINO_ROOT}/hardware/arduino/avr/cores/arduino -I${ARDUINO_ROOT}/hardware/arduino/avr/variants/leonardo ${ARDUINO_ROOT}/hardware/arduino/avr/cores/arduino/wiring.c -o ${TMPDIR}/wiring.c.o 
${ARDUINO_TOOLS}/avr-gcc -c -g -Os -w -ffunction-sections -fdata-sections  -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=10603 -DARDUINO_AVR_ESPLORA -DARDUINO_ARCH_AVR -DUSB_VID=0x2341 -DUSB_PID=0x803c -DUSB_MANUFACTURER="Unknown" '-DUSB_PRODUCT="Arduino Esplora"' -I${ARDUINO_ROOT}/hardware/arduino/avr/cores/arduino -I${ARDUINO_ROOT}/hardware/arduino/avr/variants/leonardo ${ARDUINO_ROOT}/hardware/arduino/avr/cores/arduino/wiring_digital.c -o ${TMPDIR}/wiring_digital.c.o 
${ARDUINO_TOOLS}/avr-gcc -c -g -Os -w -ffunction-sections -fdata-sections  -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=10603 -DARDUINO_AVR_ESPLORA -DARDUINO_ARCH_AVR -DUSB_VID=0x2341 -DUSB_PID=0x803c -DUSB_MANUFACTURER="Unknown" '-DUSB_PRODUCT="Arduino Esplora"' -I${ARDUINO_ROOT}/hardware/arduino/avr/cores/arduino -I${ARDUINO_ROOT}/hardware/arduino/avr/variants/leonardo ${ARDUINO_ROOT}/hardware/arduino/avr/cores/arduino/wiring_pulse.c -o ${TMPDIR}/wiring_pulse.c.o 
${ARDUINO_TOOLS}/avr-g++ -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=10603 -DARDUINO_AVR_ESPLORA -DARDUINO_ARCH_AVR -DUSB_VID=0x2341 -DUSB_PID=0x803c -DUSB_MANUFACTURER="Unknown" '-DUSB_PRODUCT="Arduino Esplora"' -I${ARDUINO_ROOT}/hardware/arduino/avr/cores/arduino -I${ARDUINO_ROOT}/hardware/arduino/avr/variants/leonardo ${ARDUINO_ROOT}/hardware/arduino/avr/cores/arduino/HID.cpp -o ${TMPDIR}/HID.cpp.o 
${ARDUINO_TOOLS}/avr-g++ -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=10603 -DARDUINO_AVR_ESPLORA -DARDUINO_ARCH_AVR -DUSB_VID=0x2341 -DUSB_PID=0x803c -DUSB_MANUFACTURER="Unknown" '-DUSB_PRODUCT="Arduino Esplora"' -I${ARDUINO_ROOT}/hardware/arduino/avr/cores/arduino -I${ARDUINO_ROOT}/hardware/arduino/avr/variants/leonardo ${ARDUINO_ROOT}/hardware/arduino/avr/cores/arduino/HardwareSerial1.cpp -o ${TMPDIR}/HardwareSerial1.cpp.o 
${ARDUINO_TOOLS}/avr-g++ -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=10603 -DARDUINO_AVR_ESPLORA -DARDUINO_ARCH_AVR -DUSB_VID=0x2341 -DUSB_PID=0x803c -DUSB_MANUFACTURER="Unknown" '-DUSB_PRODUCT="Arduino Esplora"' -I${ARDUINO_ROOT}/hardware/arduino/avr/cores/arduino -I${ARDUINO_ROOT}/hardware/arduino/avr/variants/leonardo ${ARDUINO_ROOT}/hardware/arduino/avr/cores/arduino/abi.cpp -o ${TMPDIR}/abi.cpp.o 
${ARDUINO_TOOLS}/avr-g++ -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=10603 -DARDUINO_AVR_ESPLORA -DARDUINO_ARCH_AVR -DUSB_VID=0x2341 -DUSB_PID=0x803c -DUSB_MANUFACTURER="Unknown" '-DUSB_PRODUCT="Arduino Esplora"' -I${ARDUINO_ROOT}/hardware/arduino/avr/cores/arduino -I${ARDUINO_ROOT}/hardware/arduino/avr/variants/leonardo ${ARDUINO_ROOT}/hardware/arduino/avr/cores/arduino/HardwareSerial3.cpp -o ${TMPDIR}/HardwareSerial3.cpp.o 
${ARDUINO_TOOLS}/avr-g++ -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=10603 -DARDUINO_AVR_ESPLORA -DARDUINO_ARCH_AVR -DUSB_VID=0x2341 -DUSB_PID=0x803c -DUSB_MANUFACTURER="Unknown" '-DUSB_PRODUCT="Arduino Esplora"' -I${ARDUINO_ROOT}/hardware/arduino/avr/cores/arduino -I${ARDUINO_ROOT}/hardware/arduino/avr/variants/leonardo ${ARDUINO_ROOT}/hardware/arduino/avr/cores/arduino/Tone.cpp -o ${TMPDIR}/Tone.cpp.o 
${ARDUINO_TOOLS}/avr-g++ -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=10603 -DARDUINO_AVR_ESPLORA -DARDUINO_ARCH_AVR -DUSB_VID=0x2341 -DUSB_PID=0x803c -DUSB_MANUFACTURER="Unknown" '-DUSB_PRODUCT="Arduino Esplora"' -I${ARDUINO_ROOT}/hardware/arduino/avr/cores/arduino -I${ARDUINO_ROOT}/hardware/arduino/avr/variants/leonardo ${ARDUINO_ROOT}/hardware/arduino/avr/cores/arduino/new.cpp -o ${TMPDIR}/new.cpp.o 
${ARDUINO_TOOLS}/avr-g++ -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=10603 -DARDUINO_AVR_ESPLORA -DARDUINO_ARCH_AVR -DUSB_VID=0x2341 -DUSB_PID=0x803c -DUSB_MANUFACTURER="Unknown" '-DUSB_PRODUCT="Arduino Esplora"' -I${ARDUINO_ROOT}/hardware/arduino/avr/cores/arduino -I${ARDUINO_ROOT}/hardware/arduino/avr/variants/leonardo ${ARDUINO_ROOT}/hardware/arduino/avr/cores/arduino/HardwareSerial2.cpp -o ${TMPDIR}/HardwareSerial2.cpp.o 
${ARDUINO_TOOLS}/avr-g++ -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=10603 -DARDUINO_AVR_ESPLORA -DARDUINO_ARCH_AVR -DUSB_VID=0x2341 -DUSB_PID=0x803c -DUSB_MANUFACTURER="Unknown" '-DUSB_PRODUCT="Arduino Esplora"' -I${ARDUINO_ROOT}/hardware/arduino/avr/cores/arduino -I${ARDUINO_ROOT}/hardware/arduino/avr/variants/leonardo ${ARDUINO_ROOT}/hardware/arduino/avr/cores/arduino/CDC.cpp -o ${TMPDIR}/CDC.cpp.o 
${ARDUINO_TOOLS}/avr-g++ -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=10603 -DARDUINO_AVR_ESPLORA -DARDUINO_ARCH_AVR -DUSB_VID=0x2341 -DUSB_PID=0x803c -DUSB_MANUFACTURER="Unknown" '-DUSB_PRODUCT="Arduino Esplora"' -I${ARDUINO_ROOT}/hardware/arduino/avr/cores/arduino -I${ARDUINO_ROOT}/hardware/arduino/avr/variants/leonardo ${ARDUINO_ROOT}/hardware/arduino/avr/cores/arduino/IPAddress.cpp -o ${TMPDIR}/IPAddress.cpp.o 
${ARDUINO_TOOLS}/avr-g++ -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=10603 -DARDUINO_AVR_ESPLORA -DARDUINO_ARCH_AVR -DUSB_VID=0x2341 -DUSB_PID=0x803c -DUSB_MANUFACTURER="Unknown" '-DUSB_PRODUCT="Arduino Esplora"' -I${ARDUINO_ROOT}/hardware/arduino/avr/cores/arduino -I${ARDUINO_ROOT}/hardware/arduino/avr/variants/leonardo ${ARDUINO_ROOT}/hardware/arduino/avr/cores/arduino/HardwareSerial0.cpp -o ${TMPDIR}/HardwareSerial0.cpp.o 
${ARDUINO_TOOLS}/avr-g++ -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=10603 -DARDUINO_AVR_ESPLORA -DARDUINO_ARCH_AVR -DUSB_VID=0x2341 -DUSB_PID=0x803c -DUSB_MANUFACTURER="Unknown" '-DUSB_PRODUCT="Arduino Esplora"' -I${ARDUINO_ROOT}/hardware/arduino/avr/cores/arduino -I${ARDUINO_ROOT}/hardware/arduino/avr/variants/leonardo ${ARDUINO_ROOT}/hardware/arduino/avr/cores/arduino/WMath.cpp -o ${TMPDIR}/WMath.cpp.o 
${ARDUINO_TOOLS}/avr-g++ -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=10603 -DARDUINO_AVR_ESPLORA -DARDUINO_ARCH_AVR -DUSB_VID=0x2341 -DUSB_PID=0x803c -DUSB_MANUFACTURER="Unknown" '-DUSB_PRODUCT="Arduino Esplora"' -I${ARDUINO_ROOT}/hardware/arduino/avr/cores/arduino -I${ARDUINO_ROOT}/hardware/arduino/avr/variants/leonardo ${ARDUINO_ROOT}/hardware/arduino/avr/cores/arduino/Print.cpp -o ${TMPDIR}/Print.cpp.o 
${ARDUINO_TOOLS}/avr-g++ -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=10603 -DARDUINO_AVR_ESPLORA -DARDUINO_ARCH_AVR -DUSB_VID=0x2341 -DUSB_PID=0x803c -DUSB_MANUFACTURER="Unknown" '-DUSB_PRODUCT="Arduino Esplora"' -I${ARDUINO_ROOT}/hardware/arduino/avr/cores/arduino -I${ARDUINO_ROOT}/hardware/arduino/avr/variants/leonardo ${ARDUINO_ROOT}/hardware/arduino/avr/cores/arduino/Stream.cpp -o ${TMPDIR}/Stream.cpp.o 
${ARDUINO_TOOLS}/avr-g++ -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=10603 -DARDUINO_AVR_ESPLORA -DARDUINO_ARCH_AVR -DUSB_VID=0x2341 -DUSB_PID=0x803c -DUSB_MANUFACTURER="Unknown" '-DUSB_PRODUCT="Arduino Esplora"' -I${ARDUINO_ROOT}/hardware/arduino/avr/cores/arduino -I${ARDUINO_ROOT}/hardware/arduino/avr/variants/leonardo ${ARDUINO_ROOT}/hardware/arduino/avr/cores/arduino/WString.cpp -o ${TMPDIR}/WString.cpp.o 
${ARDUINO_TOOLS}/avr-g++ -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=10603 -DARDUINO_AVR_ESPLORA -DARDUINO_ARCH_AVR -DUSB_VID=0x2341 -DUSB_PID=0x803c -DUSB_MANUFACTURER="Unknown" '-DUSB_PRODUCT="Arduino Esplora"' -I${ARDUINO_ROOT}/hardware/arduino/avr/cores/arduino -I${ARDUINO_ROOT}/hardware/arduino/avr/variants/leonardo ${ARDUINO_ROOT}/hardware/arduino/avr/cores/arduino/USBCore.cpp -o ${TMPDIR}/USBCore.cpp.o 
${ARDUINO_TOOLS}/avr-g++ -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=10603 -DARDUINO_AVR_ESPLORA -DARDUINO_ARCH_AVR -DUSB_VID=0x2341 -DUSB_PID=0x803c -DUSB_MANUFACTURER="Unknown" '-DUSB_PRODUCT="Arduino Esplora"' -I${ARDUINO_ROOT}/hardware/arduino/avr/cores/arduino -I${ARDUINO_ROOT}/hardware/arduino/avr/variants/leonardo ${ARDUINO_ROOT}/hardware/arduino/avr/cores/arduino/HardwareSerial.cpp -o ${TMPDIR}/HardwareSerial.cpp.o 
${ARDUINO_TOOLS}/avr-g++ -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=10603 -DARDUINO_AVR_ESPLORA -DARDUINO_ARCH_AVR -DUSB_VID=0x2341 -DUSB_PID=0x803c -DUSB_MANUFACTURER="Unknown" '-DUSB_PRODUCT="Arduino Esplora"' -I${ARDUINO_ROOT}/hardware/arduino/avr/cores/arduino -I${ARDUINO_ROOT}/hardware/arduino/avr/variants/leonardo ${ARDUINO_ROOT}/hardware/arduino/avr/cores/arduino/main.cpp -o ${TMPDIR}/main.cpp.o 
${ARDUINO_TOOLS}/avr-ar rcs ${TMPDIR}/core.a ${TMPDIR}/wiring_shift.c.o 
${ARDUINO_TOOLS}/avr-ar rcs ${TMPDIR}/core.a ${TMPDIR}/WInterrupts.c.o 
${ARDUINO_TOOLS}/avr-ar rcs ${TMPDIR}/core.a ${TMPDIR}/hooks.c.o 
${ARDUINO_TOOLS}/avr-ar rcs ${TMPDIR}/core.a ${TMPDIR}/wiring_analog.c.o 
${ARDUINO_TOOLS}/avr-ar rcs ${TMPDIR}/core.a ${TMPDIR}/wiring.c.o 
${ARDUINO_TOOLS}/avr-ar rcs ${TMPDIR}/core.a ${TMPDIR}/wiring_digital.c.o 
${ARDUINO_TOOLS}/avr-ar rcs ${TMPDIR}/core.a ${TMPDIR}/wiring_pulse.c.o 
${ARDUINO_TOOLS}/avr-ar rcs ${TMPDIR}/core.a ${TMPDIR}/HID.cpp.o 
${ARDUINO_TOOLS}/avr-ar rcs ${TMPDIR}/core.a ${TMPDIR}/HardwareSerial1.cpp.o 
${ARDUINO_TOOLS}/avr-ar rcs ${TMPDIR}/core.a ${TMPDIR}/abi.cpp.o 
${ARDUINO_TOOLS}/avr-ar rcs ${TMPDIR}/core.a ${TMPDIR}/HardwareSerial3.cpp.o 
${ARDUINO_TOOLS}/avr-ar rcs ${TMPDIR}/core.a ${TMPDIR}/Tone.cpp.o 
${ARDUINO_TOOLS}/avr-ar rcs ${TMPDIR}/core.a ${TMPDIR}/new.cpp.o 
${ARDUINO_TOOLS}/avr-ar rcs ${TMPDIR}/core.a ${TMPDIR}/HardwareSerial2.cpp.o 
${ARDUINO_TOOLS}/avr-ar rcs ${TMPDIR}/core.a ${TMPDIR}/CDC.cpp.o 
${ARDUINO_TOOLS}/avr-ar rcs ${TMPDIR}/core.a ${TMPDIR}/IPAddress.cpp.o 
${ARDUINO_TOOLS}/avr-ar rcs ${TMPDIR}/core.a ${TMPDIR}/HardwareSerial0.cpp.o 
${ARDUINO_TOOLS}/avr-ar rcs ${TMPDIR}/core.a ${TMPDIR}/WMath.cpp.o 
${ARDUINO_TOOLS}/avr-ar rcs ${TMPDIR}/core.a ${TMPDIR}/Print.cpp.o 
${ARDUINO_TOOLS}/avr-ar rcs ${TMPDIR}/core.a ${TMPDIR}/Stream.cpp.o 
${ARDUINO_TOOLS}/avr-ar rcs ${TMPDIR}/core.a ${TMPDIR}/WString.cpp.o 
${ARDUINO_TOOLS}/avr-ar rcs ${TMPDIR}/core.a ${TMPDIR}/USBCore.cpp.o 
${ARDUINO_TOOLS}/avr-ar rcs ${TMPDIR}/core.a ${TMPDIR}/HardwareSerial.cpp.o 
${ARDUINO_TOOLS}/avr-ar rcs ${TMPDIR}/core.a ${TMPDIR}/main.cpp.o 
${ARDUINO_TOOLS}/avr-gcc -w -Os -Wl,--gc-sections -mmcu=atmega32u4 -o ${TMPDIR}/joystick.cpp.elf ${TMPDIR}/joystick.cpp.o ${TMPDIR}/Esplora/Esplora.cpp.o ${TMPDIR}/core.a -L${TMPDIR} -lm 
${ARDUINO_TOOLS}/avr-objcopy -O ihex -j .eeprom --set-section-flags=.eeprom=alloc,load --no-change-warnings --change-section-lma .eeprom=0 ${TMPDIR}/joystick.cpp.elf ${TMPDIR}/joystick.cpp.eep 
${ARDUINO_TOOLS}/avr-objcopy -O ihex -R .eeprom ${TMPDIR}/joystick.cpp.elf ${TMPDIR}/joystick.cpp.hex 

${ARDUINO_TOOLS}/avrdude -C${ARDUINO_ROOT}/hardware/tools/avr/etc/avrdude.conf -v -patmega32u4 -cavr109 -P/dev/ttyACM0 -b57600 -D -Uflash:w:${TMPDIR}/joystick.cpp.hex:i 
